spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryfteria-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
cryfteria:
  jwt:
    config:
      secret: 397A24432646294A404E635266556A586E3272357538782F4125442A472D4B61
      expiration-hours: 100
  cross-origin-patterns: http://localhost:3000
  localstorage:
    path:
      images: /home/leroy/web3Projects/Cryfteria/images/
application:
  title: Cryfteria backend
  version: 0.0.1
  creator: Bebra inc.